# Site Info
title: 숨의 페이지
tagline: '숨의 페이지'
description: '공부기록'
baseurl: ""
url: https://developersoom.github.io/
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: SOOM
  description: 숨! 프론트엔드 꿈나무! 
  contact:
    # linkedin:  
    # github:   
    # facebook: 
    # twitter:   
    # weibo:    
    email:    mailto:developer.soom@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    #- { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    - { 필름 : '/blog/categories/#필름' }
    #- { Django: '/blog/categories/#django' }
    #- { python: '/blog/categories/#python' }
    #- { javascript: '/blog/categories/#javascript' }
    #- { nodejs: '/blog/categories/#nodejs' }
    #- { MySQL: '/blog/categories/#MySQL' }
    #- { 알고리즘 문제풀이: '/blog/categories/#알고리즘-문제풀이' }
    #- { git: '/blog/categories/#git' }
    #- { firebase: '/blog/categories/#firebase' }
    #- { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  #About:
   # - '/about/'
  #Search:
   # - '/search/'



# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: # leave blank if you don't want google analytics
disqus_short_name:  # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
